<?php 
	$main = '<main>'
		. '<div class="container">'
		. 	'<div class="row">'
		. 		'<div class="col-9 main__content">'
		.     '<div class="row">'
		.			'<?php '
		.			'	$articles = get_all_posts(); '
		.			'	while($article = mysqli_fetch_assoc($articles)) { '
		.			'		echo "<div class=\"col-6\">"; '
		.			'		echo "<img src=\"{$article["img_link"]}\">"; '
		.			'		$safe_article_id = urlencode($article["id"]); '
		.     '   echo "<a href=\"single.php?article={$safe_article_id}\">";  '
		.     '   echo htmlentities($article["title"]); '
		.			'		echo "</a>"; '
		.			'		echo "<p>"; '
		.			'		echo htmlentities($article["excerpt"]); '
		.			'		echo "</p>"; '
		.			'		echo "</div>"; '
		.			'	} '
		.			' ?>'
		. 		'</div>'
		. 		'</div>'
		. 		'<div class="col-3 bg-info sidebar" style="height:100px;">'
		.     '<h4>Подобные посты</h4>'
		. 		'</div>' 
		. 	'</div>'
		. '</div>'
		.'</main>';
