<?php
	return ' <?php function get_all_posts(){ '
	. '	global $connection; '
		. '	$query  = "SELECT * "; '
		. '	$query .= "FROM cat_articles "; '
		. '	$query .= "ORDER BY id DESC"; '
		. '	$articles_set = mysqli_query($connection, $query); '
		. '	return $articles_set; '
	. '	} '
	. '	function get_all_categories(){ '
		. '	global $connection; '
		. '	$query  = "SELECT * "; '
		. '	$query .= "FROM categories "; ' 
		. '	$query .= "ORDER BY id ASC";  '
		. '	$categories_set = mysqli_query($connection, $query); '
		. '	return $categories_set; '
	. '	} '
	. '	function get_posts_by_category($category_id){ '
		. '	global $connection; '
		. '	$safe_category = mysqli_real_escape_string($connection, $category); '
		. '	$query  = "SELECT * "; '
		. '	$query .= "FROM cat_articles "; '
		. '	$query .= "WHERE category = {$safe_category} "; '
		. '	$query .= "ORDER BY id DESC"; '
		. '	$articles_set = mysqli_query($connection, $query); '
		. '	return $articles_set; '
	. '	} '
	. '	function get_post_by_id($id){ '
		. '	global $connection; '
		. '	$query  = "SELECT * "; '
		. '	$query .= "FROM cat_articles "; '
		. '	$query .= "WHERE id = {$id} "; '
		. '	$query .= "ORDER BY id DESC"; '
		. '	$article = mysqli_query($connection, $query); '
		. '	return $article; '
	. '	} ?>';
?>

	
